project:
  type: website
  output-dir: docs

website:
  title: "Data Lab Zone"
  image: images/logo.png
  favicon: images/favicon.png
  twitter-card: 
    site: "@ningli3739"
  open-graph: true
  #publish site on quarto pub use site-path
  #site-path: "/data-lab-zone/"
  #publish site on netlify use site-url
  #site-url: "https://datalabzone.com/"
  repo-url: "https://github.com/NING3739/datalabzone"
  repo-actions: 
     - edit
     - issue
  back-to-top-navigation: true
  google-analytics: 
    anonymize-ip: true
    tracking-id: "G-QN8B58NY2E"

  navbar:
    logo: images/logo.png
    logo-alt: "Data Lab Zone brand"
    title: false
    collapse-below: lg
    right:
      - posts/index.qmd
      - series/index.qmd
      - projects/index.qmd
      - talks/index.qmd
      - text: "Resources"
        href: resources/index.qmd
      - text: "About" 
        menu:
          - text: "About Me"
            href: about.qmd
          - text: "FAQ"
            href: faq.qmd
  
  page-footer:
     left: "&copy; 2023 [DLZ](index.qmd) create with ❤️ by [NING](about.qmd)."
         
     right: 
       - href: https://github.com/NING3739/datalabzone
         icon: github
         aria-label: GitHub
       - href: https://twitter.com/ningli3739
         icon: twitter
         aria-label: Twitter
       - href: mailto:ln729500172@outlook.com
         icon: envelope

# lightbox and webr extenation 
filters:
  - lightbox
  - webr
  - shinylive
lightbox: auto  

format:
  html:
    theme: 
      - lux
      - dlz.scss
    css: dlz.css
    code-overflow: scroll
    code-link: true
    code-line-numbers: false
    code-block-bg: "#F0F0F0"
    code-block-border-left: "#4bbf73"
    date-format: MMM DD, YYYY
    highlight-style: pygments
    toc: true
    toc-depth: 2
    grid:
      body-width: 1000px
      margin-width: 250px
  
comments: 
  giscus: 
    repo: NING3739/my-personal-website
    repo-id: R_kgDOIYBxAA
    category: Comments
    category-id: DIC_kwDOIYBxAM4CS2io
    mapping: url
    input-position: bottom
    theme: light_high_contrast

execute:
  freeze: auto
