---
title: "Mathematics in R Markdown"
date: "2023-02-07"
author: NING LI
categories: [Markdown, LaTex]
image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8TWF0aCUyMEZvcm11bHNhfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60"
description: "Write math formulas by LaTex in R Markdown."
code-line-numbers: false
license: CC BY-NC
---

The ability to beautifully and accurately write mathematical expressions is crucial to many fields, particularly in scientific research. Luckily, R Markdown provides an excellent platform for doing this, thanks to its compatibility with LaTeX, a popular typesetting system renowned for high-quality typesetting of mathematical and scientific content.

# Mathematical Formulas

To write mathematical formulas in R Markdown, we use LaTeX syntax. This is enclosed in dollar signs (`$`) for [inline formulas]{style="color:red;"} and double dollar signs (`$$`) for [display formulas]{style="color:red;"}[^1].

[^1]: https://www.cnblogs.com/nowgood/p/latexstart.html#\_nav_4

## Inline mathematical

The formula for the area of a circle is `$A = \pi r^2$`.

And it will render as:

> $$A = \pi r^2$$

## Display Formula

The formula for the area of a circle is:

``` latex
$$
A = \pi r^2
$$
```

Which will render as:

> $$A = \pi r^2$$

## Examples

1.  *Fraction*:

``` latex
$$
\begin{align*}
\frac{a}{b}
\end{align*}
$$
```

renders as:

> $$
> \begin{align*}
> \frac{a}{b}
> \end{align*}
> $$

2.  *Exponents and Subscripts*:

we use `^` for superscripts (exponents) and `_`for subscripts.

``` latex
$$
\begin{align*}
a^{b}\\
c_{d}
\end{align*}
$$
```

renders as:

> $$
> \begin{align*}
> a^{b}\\
> c_{d}
> \end{align*}
> $$

3.  *Roots and Logarithms*:

``` latex
$$
\begin{align*}
Square\ root: \sqrt{a}\\
nth\ root: \sqrt[n]{b}\\
natural\ log: \ln{c}\\
log\ base\ n: \log_{n}{d}
\end{align*}
$$
```

renders as:

> $$
> \begin{align*}
> Square\ root: \sqrt{a}\\
> nth\ root: \sqrt[n]{b}\\
> natural\ log: \ln{c}\\
> log\ base\ n: \log_{n}{d}
> \end{align*}
> $$

4.  *Quadratic equation*:

``` latex
$$
\begin{align*}
x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}
\end{align*}
$$
```

renders as:

> $$
> \begin{align*}
> x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}
> \end{align*}
> $$

5.  *Summation*:

``` latex
$$
\begin{align*}
\sum_{i=1}^{n} i = \frac{n*(n + 1)}{2}
\end{align*}
$$
```

renders as:

> $$
> \begin{align*}
> \sum_{i=1}^{n} i = \frac{n*(n + 1)}{2}
> \end{align*}
> $$

6.  *Integral*:

``` latex
$$
\begin{align*}
\int_{0}^{\infty} e^{-x} dx = 1\\
\int_{a}^{b} f(x) \, dx
\end{align*}
$$
```

renders as:

> $$
> \begin{align*}
> \int_{0}^{\infty} e^{-x} dx = 1\\
> \int_{a}^{b} f(x) \, dx
> \end{align*}
> $$

7.  *Matrix representation*:

``` latex
$$
\begin{align*}
\begin{bmatrix}
a & b \\
c & d 
\end{bmatrix}
\end{align*}
$$

$$
\begin{pmatrix}
a & b \\
c & d 
\end{pmatrix}
$$
```

Renders as:

> $$
> \begin{align*}
> \begin{bmatrix}
> a & b \\
> c & d 
> \end{bmatrix}
> \end{align*}
> $$ $$
> \begin{align*}
> \begin{pmatrix}
> a & b \\
> c & d 
> \end{pmatrix}
> \end{align*}
> $$

8.  *Trigonometric functions*:

``` latex
$$
\begin{align*}
Sine: \sin(x)\\ 
Cosine: \cos(x)\\ 
Tangent: \tan(x)\\ 
Cotangent: \cot(x)\\ 
Secant: \sec(x)\\ 
Cosecant: \csc(x) \\ 
Degree: 30^\circ
\end{align*}
$$
```

renders as:

> $$
> \begin{align*}
> Sine: \sin(x)\\ 
> Cosine: \cos(x)\\ 
> Tangent: \tan(x)\\ 
> Cotangent: \cot(x)\\ 
> Secant: \sec(x)\\ 
> Cosecant: \csc(x) \\ 
> Degree: 30^\circ
> \end{align*}
> $$

9.  *Inverse trigonometric functions*:

``` latex
$$
\\begin{flalign}
Inverse\ sine (arcsine): \arcsin(x) &\\
Inverse\ cosine (arccosine): \arccos(x) &\\
Inverse\ tangent (arctangent): \arctan(x) &
\end{flalign}
$$
```

render as:

> $$
> \small
> \begin{flalign*}
> \text{Inverse sine (arcsine):} \quad & \arcsin(x) &\\
> \text{Inverse cosine (arccosine):} \quad & \arccos(x) &\\
> \text{Inverse tangent (arctangent):} \quad & \arctan(x) &
> \end{flalign*}
> \small
> $$

# Mathematical Symbols

R Markdown (through LaTeX) provides a wealth of mathematical symbols. Here are some of the most commonly used ones:

| Symbol            | Code              |
|-------------------|-------------------|
| $+$               | `+`               |
| $-$               | `-`               |
| $\times$          | `\times`          |
| $\div$            | `\div`            |
| $\pm$             | `\pm`             |
| $\cdot$           | `\cdot`           |
| $\circ$           | `\circ`           |
| $\sqrt{x}$        | `\sqrt{x}`        |
| $\frac{a}{b}$     | `\frac{a}{b}`     |
| $\sum$            | `\sum`            |
| $\prod$           | `\prod`           |
| $\int$            | `\int`            |
| $\partial$        | `\partial`        |
| $\infty$          | `\infty`          |
| $\forall$         | `\forall`         |
| $\exists$         | `\exists`         |
| $\Rightarrow$     | `\Rightarrow`     |
| $\Leftrightarrow$ | `\Leftrightarrow` |
| $\to$             | `\to`             |
| $\subset$         | `\subset`         |
| $\supset$         | `\supset`         |
| $\subseteq$       | `\subseteq`       |
| $\supseteq$       | `\supseteq`       |
| $\notin$          | `\notin`          |
| $\neq$            | `\neq`            |
| $\approx$         | `\approx`         |
| $\equiv$          | `\equiv`          |
| $\leq$            | `\leq`            |
| $\geq$            | `\geq`            |
| $\ll$             | `\ll`             |
| $\gg$             | `\gg`             |
| $\alpha$          | `\alpha`          |
| $\beta$           | `\beta`           |
| $\gamma$          | `\gamma`          |
| $\delta$          | `\delta`          |
| $\epsilon$        | `\epsilon`        |
| $\zeta$           | `\zeta`           |
| $\eta$            | `\eta`            |
| $\theta$          | `\theta`          |
| $\iota$           | `\iota`           |
| $\kappa$          | `\kappa`          |
| $\lambda$         | `\lambda`.        |
| $\mu$             | `\mu`             |
| $\nu$             | `\nu`             |
| $\xi$             | `\xi`             |
| $\pi$             | `\pi`             |
| $\rho$            | `\rho`            |
| $\sigma$          | `\sigma`          |
| $\tau$            | `\tau`            |
| $\upsilon$        | `\upsilon`        |
| $\phi$            | `\phi`            |
| $\chi$            | `\chi`            |
| $\psi$            | `\psi`            |
| $\omega$          | `\omega`          |
| $\Gamma$          | `\Gamma`          |
| $\Delta$          | `\Delta`          |
| $\Theta$          | `\Theta`          |
| $\Lambda$         | `\Lambda`         |
| $\Xi$             | `\Xi`             |
| $\Pi$             | `\Pi`             |
| $\Sigma$          | `\Sigma`          |
| $\Phi$            | `\Phi`            |
| $\Psi$            | `\Psi`            |
| $\Omega$          | `\Omega`          |
